
package Citas_Medicas;
import javax.swing.table.DefaultTableModel;
public class VistaMedico extends javax.swing.JFrame {

   private ListaCitas listaCitas;
      
    public VistaMedico(ListaCitas listaCitas) {
         this.listaCitas = listaCitas;
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnCargarCitas = new javax.swing.JButton();
        btnMarcarComoAtendido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCargarCitas.setText("Cargar Citas");
        btnCargarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCitasActionPerformed(evt);
            }
        });

        btnMarcarComoAtendido.setText("Marcar como atendido");
        btnMarcarComoAtendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarComoAtendidoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Cita", "DNI", "Nombre", "Telefono", "Edad", "Sexo", "Ciudad", "Especialidad", "Fecha", "N Consultorio", "Doctor", "Atendido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarCitas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMarcarComoAtendido, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMarcarComoAtendido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarCitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
            VistaPrincipal vistaprincipal = new VistaPrincipal(listaCitas);
        vistaprincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


   
     
    private void btnMarcarComoAtendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarComoAtendidoActionPerformed
  int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String codigoCita = (String) jTable1.getValueAt(selectedRow, 0);
            Cita cita = listaCitas.buscarCita(codigoCita);
            if (cita != null) {
                cita.setAtendido(true);
                btnCargarCitasActionPerformed(null); // Recargar la tabla
            }
        }
    
    }//GEN-LAST:event_btnMarcarComoAtendidoActionPerformed

    private void btnCargarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCitasActionPerformed
   
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de cargar citas

        for (Cita cita : listaCitas.getCitas()) {
            model.addRow(new Object[]{
                cita.getCodigoCita(), cita.getDni(), cita.getNombre(), cita.getTelefono(), cita.getEdad(),
                cita.getSexo(), cita.getCiudad(), cita.getEspecialidad(), cita.getFecha(), cita.getNumeroConsultorio(),
                cita.getDoctor(), cita.isAtendido()
            });
        }
    }//GEN-LAST:event_btnCargarCitasActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarCitas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMarcarComoAtendido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
